name: example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  firebase_auth: ^0.18.1+1
  cloud_firestore: ^0.14.1+2
  firebase_storage: ^4.0.1
  firebase_core: ^0.5.0

  get: ^3.12.1
  # pdf: ^1.11.2
  # intl: ^0.16.1 # 国际化
  http: ^0.12.2
  # lottie: ^0.6.0
  # shimmer: ^1.1.1 # 白叶占位层

  # location: ^3.0.2
  # fl_chart: ^0.11.1 # 图表
  provider: ^4.3.2+2
  # animations: ^1.1.2 # 大型页面动画
  animate_do: ^1.7.3 # 局部动画执行
  # device_info: ^0.4.2+8 # 设备信息

  app_settings: ^4.0.4 # 打开设置
  google_fonts: ^1.1.0 # 好看字体
  connectivity: ^0.4.9+2 # 检查网络连接
  # url_launcher: ^5.5.3 # 打开浏览器、电邮、电话
  # fluttertoast: ^7.1.1
  # image_picker: ^0.6.7+11 
  # video_player: ^0.11.0

  # path_provider: ^1.6.18 # 寻找手机文件夹
  # flutter_swiper: ^1.1.6
  # auto_size_text: ^2.1.0 # 自动调整文本大小以完全适合其范围
  pull_to_refresh: ^1.6.2 # 下拉刷新
  carousel_slider: ^2.3.1 # 轮播展示
  flutter_spinkit: ^4.1.2+1 # 加载动画
  # sliding_up_panel: ^1.0.2 # 上滑抽出一个面板
  # flutter_slidable: ^0.5.7 # 横向滑动操作视图

  # animated_text_kit: ^2.3.0 # 字体动画
  convex_bottom_bar: ^2.5.1 # 凸显底部bar 效果
  # permission_handler: ^5.0.1+1 # 手机权限状态控制插件
  flutter_screenutil: ^3.1.1
  shared_preferences: ^0.5.12

  # flare_splash_screen: ^3.0.1 # 启动页
  # font_awesome_flutter: ^8.8.1
  flutter_form_builder: ^3.13.5
  cached_network_image: ^ 2.3.2+1
  curved_navigation_bar: ^0.3.4
  # smooth_page_indicator: ^0.2.0
  # flutter_launcher_icons: ^0.8.1
  
  # flutter_staggered_grid_view: ^0.3.2
  flutter_local_notifications: ^2.0.0 # 弹框提示
  webview_flutter: ^0.3.24

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/html/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
