name: sona
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_core: ^0.5.0

  get: ^3.10.2
  dio: ^3.0.10
  pdf: ^1.11.1
  hive: ^1.4.4 # 键值对数据库
  intl: ^0.16.1 # 国际化
  http: ^0.12.2
  mobx: ^1.2.1+2 # 模型层数据获取
  share: ^0.6.5
  get_it: ^5.0.1 # 数据的依赖注入
  rxdart: ^0.24.1 # 观察者模式数据处理
  lottie: ^0.6.0 # 0.7.0+1
  shimmer: ^1.1.1 # 白叶占位层
  location: ^3.0.2
  
  
  fl_chart: ^0.11.1 # 图表
  provider: ^4.3.2+2
  animations: ^1.1.2 # 大型页面动画
  
  geolocator: ^6.0.0+4
  animate_do: ^1.7.3 # 局部动画执行
  device_info: ^0.4.2+8 # 设备信息
  flutter_svg: ^0.19.0
  
  app_settings: ^4.0.4 # 打开设置
  google_fonts: ^1.1.0 # 好看字体
  connectivity: ^0.4.9+2 # 检查网络连接
  url_launcher: ^5.5.3 # 打开浏览器、电邮、电话
  flutter_bloc: ^6.0.5 # 数据暂存且即时更新 类似 provider
  fluttertoast: ^7.1.1
  image_picker: ^0.6.7+7 
  video_player: ^0.10.12+2
  flutter_mobx: ^1.1.0+2
  
  path_provider: ^1.6.14 # 寻找手机文件夹
  flutter_swiper: ^1.1.6
  device_preview: ^0.4.8
  auto_size_text: ^2.1.0 # 自动调整文本大小以完全适合其范围
  pull_to_refresh: ^1.6.2 # 下拉刷新
  carousel_slider: ^2.2.1 # 轮播展示
  flutter_spinkit: ^4.1.2+1 # 加载动画
  
  sliding_up_panel: ^1.0.2 # 上滑抽出一个面板
  flutter_slidable: ^0.5.7 # 横向滑动操作视图
  animated_text_kit: ^2.2.0 # 字体动画
  convex_bottom_bar: ^2.4.1 # 凸显底部bar 效果
  gzx_dropdown_menu: ^2.1.0 # 下拉菜单
   
  permission_handler: ^5.0.1+1 # 手机权限状态控制插件
  flutter_screenutil: ^2.3.1
  responsive_builder: ^0.3.0 
  shared_preferences: ^0.5.10 # 本地储存
  flare_splash_screen: ^3.0.1 # 启动页

  font_awesome_flutter: ^8.8.1
  responsive_framework: ^0.0.8
  flutter_form_builder: ^3.13.5
  cached_network_image: ^ 2.3.2+1
  curved_navigation_bar: ^0.3.4
  smooth_page_indicator: ^0.2.0 # Scrolling dots effect
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.8.0 # 应用图标设置

  flutter_staggered_grid_view: ^0.3.2
  flutter_local_notifications: ^1.4.4+4 # 弹框提示


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/product/
    - assets/pageFx/
    - assets/imgs/
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
